error: quota limit exceeded
- observed repeating pageTokens for different queries
- wrote getPageNumbers.py for scraping the first 10 pageTokens (to maintain most recent 500 videos)
- ran out of quota limit (each serach call costs 100, daily limit of 10000, ran out due to testing the API request)